service: tu-webhooks

frameworkVersion: '2'

provider:
  name: aws
  runtime: ruby2.7

  stage: dev
  region: us-east-1

  tags:
    app: techuncensored

  environment:
    GEM_PATH: '/var/task/vendor/bundle/ruby/2.6.0'

#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

functions:
  github:
    handler: handler.github
    events:
      - http:
          path: github
          method: get
