service: tu-challenges # NOTE: update this with your service name

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

  stage: dev
  region: us-east-1

  tags:
    app: techuncensored

#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

functions:
  challenges:
    handler: handler.challenges
    events:
      - http:
          path: challenges
          method: get
  challenge:
    handler: handler.challenge
    events:
      - http:
          path: challenge/{id}/
          method: get
          request:
            parameters:
              paths:
                id: true
  challengesrc:
    handler: handler.challengesrc
    events:
      - http:
          path: challenge/{id}/src
          method: get
          request:
            parameters:
              paths:
                id: true